### ISSUE TITLE
Unreachable code               

### ISSUE THREAD

**Issue by timothypratley** [jkk/verily#8]
Since upgrading Clojure/ClojureScript, I now get a compiler warning:
Mar 15, 2016 12:36:22 PM com.google.javascript.jscomp.LoggerErrorManager println
WARNING: /Users/timothypratley/.../target/cljsbuild-compiler-1/jkkramer/verily.js:716: WARNING - unreachable code
}catch (e12458){if((e12458 instanceof Error)){
 ^

Mar 15, 2016 12:36:22 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
    [org.clojure/clojurescript "1.7.228"]
    [org.clojure/clojure "1.8.0"]

**Comment by iku000888** [comment]
Could you perhaps dig a bit deeper and track it to a line sourcecode?
(Have not gotten my hands dirty with verily yet...)

**Comment by timothypratley** [comment]
Sure, here is the root of the issue:
https://github.com/jkk/verily/pull/10

There is an empty CLJS code path which causes the warning.
Removing it resolves the issue.
